#!/usr/bin/env bash

usage() {
  echo "USAGE: $0 <11|17>"
  if [[ -n "$1" ]]; then
    echo
    echo "$1"
  fi
  exit 1
}

case "$1" in
    11|17)
      jdkPath="$(dpkg-query -L "openjdk-${1}-jre-headless" | grep 'modules$')"
      cpid reindex jimage "jdk${1}" "$jdkPath"
      ;;
    ""|-h|--help)
      usage
      ;;
    *)
      usage "Unknown JDK version. Only works with 11 and 17."
      ;;
esac

